export const FETCH_INSTRUMENTS = 'FETCH_INSTRUMENTS'
export const FETCH_INSTRUMENTS_SUCCESS = 'FETCH_INSTRUMENTS_SUCCESS'
export const FETCH_INSTRUMENTS_FAILURE = 'FETCH_INSTRUMENTS_FAILURE'
export const RESET_INSTRUMENTS = 'RESET_INSTRUMENTS'

export const DELETE_INSTRUMENT = 'DELETE_INSTRUMENT'
export const DELETE_INSTRUMENT_SUCCESS = 'DELETE_INSTRUMENT_SUCCESS'
export const DELETE_INSTRUMENT_FAILURE = 'DELETE_INSTRUMENT_FAILURE'
export const RESET_DELETED_INSTRUMENT = 'RESET_DELETED_INSTRUMENT'
