version: '2'

services:
    db:
        image: postgres:9-alpine
        volumes:
            - ./docker/db/data:/var/lib/postgresql/data
        ports:
            - "${DB_PORT}:5432"
        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_DB=${DB_NAME}
            - PGDATA=/var/lib/postgresql/data/pgdata

    express:
        build:
            context: docker/express
        command: bash -c "yarn && DEBUG=express:* pm2-runtime start process.json"
        ports:
            - "${EXPRESS_PORT}:3000"
        environment:
            - DB_HOSTNAME=db
            - DB_PORT=${DB_PORT}
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - TEST_DB_HOSTNAME=db
            - TEST_DB_USER=${TEST_DB_USER}
            - TEST_DB_PASSWORD=${TEST_DB_PASSWORD}
            - TEST_DB_NAME=${TEST_DB_NAME}
            - PROD_DB_PORT=${PROD_DB_PORT}
            - PROD_DB_HOSTNAME=${PROD_DB_HOSTNAME}
            - PROD_DB_USER=${PROD_DB_USER}
            - PROD_DB_PASSWORD=${PROD_DB_PASSWORD}
            - PROD_DB_NAME=${PROD_DB_NAME}
            - TEST_PORT=${TEST_PORT}
        volumes:
            - ./server:/usr/src/app
#            - ${NODE_LOG_DIR}:/home/node/.pm2/logs
        links:
            - db:postgres

    react:
        build:
          context: docker/react
        command: bash -c "yarn && yarn run start"
        ports:
            - "${REACT_PORT}:3000"
        volumes:
          - ./client:/usr/src/app
